### ISSUE TITLE
Console log error

### ISSUE THREAD

**Issue by justoverclockl** [FriendsOfFlarum/polls#43] opened 2021-06-04 08:48 UTC
https://i.ibb.co/crSRSdw/ssss.png

discuss link:
https://discuss.flarum.org/d/27517-console-error-on-101/6

```
$ php flarum info
Flarum core 1.0.1
PHP version: 7.3.28
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2                                                                                                                              , calendar, ctype, curl, dba, dom, enchant, hash, fileinfo, filter, ftp, gd, get                                                                                                                              text, gmp, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl,                                                                                                                               mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readl                                                                                                                              ine, Reflection, imap, shmop, SimpleXML, soap, sockets, sodium, exif, sysvmsg, s                                                                                                                              ysvsem, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, memc                                                                                                                              ached, ionCube Loader, Zend OPcache
+-----------------------------------+---------+--------+
| Flarum Extensions                 |         |        |
+-----------------------------------+---------+--------+
| ID                                | Version | Commit |
+-----------------------------------+---------+--------+
| flarum-flags                      | v1.0.0  |        |
| flarum-suspend                    | v1.0.0  |        |
| flarum-markdown                   | v1.0.1  |        |
| flarum-lang-italian               | 1.0.3   |        |
| justoverclock-dontgoaway          | 0.2.5   |        |
| justoverclock-guestengagement     | 0.1.7   |        |
| fof-links                         | 1.0.0   |        |
| flarum-approval                   | v1.0.0  |        |
| flarum-bbcode                     | v1.0.0  |        |
| flarum-emoji                      | v1.0.0  |        |
| flarum-lang-english               | v1.0.0  |        |
| flarum-likes                      | v1.0.0  |        |
| flarum-lock                       | v1.0.0  |        |
| flarum-mentions                   | v1.0.0  |        |
| flarum-statistics                 | v1.0.0  |        |
| flarum-sticky                     | v1.0.0  |        |
| flarum-subscriptions              | v1.0.0  |        |
| flarum-tags                       | v1.0.1  |        |
| fof-formatting                    | 1.0.0   |        |
| fof-oauth                         | 1.0.0   |        |
| fof-analytics                     | 1.0.0   |        |
| fof-share-social                  | 1.0.0   |        |
| fof-polls                         | 1.0.1   |        |
| fof-socialprofile                 | 1.0.0   |        |
| fof-user-bio                      | 1.0.0   |        |
| phenomlab-fancybox-wrapper        | 0.8     |        |
| fof-best-answer                   | 1.0.0   |        |
| flarumite-simple-discussion-views | 1.0.0   |        |
| flarum-pusher                     | v1.0.0  |        |
| askvortsov-checklist              | v1.3.1  |        |
| justoverclock-contactme           | 0.2.0   |        |
| justoverclock-visitorstat         | 0.2.0   |        |
| justoverclock-keywords            | 1.6     |        |
| malago-achievements               | 0.3.1   |        |
+-----------------------------------+---------+--------+
Base URL: https://flarum.it
Installation path: /home/customer/www/flarum.it/public_html
Debug mode: off
```

**Comment by datitisev** [comment] 2021-06-13 13:53
Duplicate of #45 (yes, that one is newer but more clear on issue). Fixed, so closing.

**Closed by datitisev** 2021-06-13 13:53 UTC
Labels: bug
