### ISSUE TITLE
Notifications panel broken

### ISSUE THREAD

**Issue by matteocontrini** [FriendsOfFlarum/polls#19] opened 2020-07-25 19:01 UTC
Hello,

it seems that on a discussion page with a poll this extension breaks the notification panel after "a while":

![image](https://user-images.githubusercontent.com/2164763/88464314-ebe2c380-ceb9-11ea-8c37-8b0ee0e3a7a8.png)

And sometimes even other UI elements:

![image](https://user-images.githubusercontent.com/2164763/88464318-f3a26800-ceb9-11ea-83ac-22a2a1088fac.png)

I've never seen this problem in other situations so it seems to be related to the poll.

**Comment by Ralkage** [comment] 2021-04-08 18:19
@matteocontrini our apologies for the extremely late reply! Are you still experiencing this issue?

**Comment by clarkwinkelmann** [comment] 2021-07-02 20:23
I was not able to replicate this during today's test session.

I notice there's a difference if you open the notifications from the homepage when the post is visible, because the poll icon will be rendered:
![image](https://user-images.githubusercontent.com/5264300/124324944-189c6200-db84-11eb-8d83-e60ac3496610.png)

However when opening the notifications from a page where the discussion hasn't been loaded yet, the poll icon is not visible:
![image](https://user-images.githubusercontent.com/5264300/124324853-f1459500-db83-11eb-9b7a-e48a71ca486c.png)

I was however not able to trigger any error.

I'm going to close this for now since we haven't found any way to reproduce since all this time. Feel free to re-open if more details are found.

**Closed by clarkwinkelmann** 2021-07-02 20:23 UTC

**Comment by matteocontrini** [comment] 2021-07-03 07:10
Hi, sorry for the delay, this has been in my inbox since April (seriously) but I still have to try to reproduce the problem.

I have the suspect that it was related to the WebSockets extension, I remember that when a new vote came there was a refresh of the UI which caused issues in multiple places.

If it happens again I'll report back, I'm not using this extension very actively now (and I need to upgrade to 1.0 before trying anything anyway).
